In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


# 1. Creating a tensor

In [3]:
# using empty
a = torch.empty(2,3)
a

tensor([[-6.0933e-09,  4.3653e-41, -6.0933e-09],
        [ 4.3653e-41,  2.6081e+20,  2.1351e+20]])

In [4]:
# check type
type(a)

torch.Tensor

In [5]:
# using zeroes
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# using ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# using rand
torch.rand(2, 3)

tensor([[0.7930, 0.9851, 0.5251],
        [0.2144, 0.9922, 0.7695]])

In [8]:
# manual seed(same values of tensors)
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2, 3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# custom tensor
torch.tensor([[1, 2, 3], [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

# 2. Tensor shapes

In [11]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
# copy tensor with same shape
torch.empty_like(x)

tensor([[    133799804493200,     133799804493200,                   0],
        [                  0,                   0, 7310593858020254331]])

# 3. Tensor Datatypes

In [14]:
x.dtype

torch.int64

In [15]:
# assign data type
torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [16]:
# convert
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [17]:
x.dtype

torch.int64

# 3. Mathematical Operations
## 1. Scaler

In [19]:
X = torch.rand(2, 3)
X

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [21]:
# scaler -> addition
X + 2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [22]:
# scaler -> subtraction
X - 1

tensor([[-0.2882, -0.2124, -0.5817],
        [-0.0986, -0.0031, -0.2435]])

In [23]:
# scaler -> multiply
X * 2

tensor([[1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [24]:
# scaler -> division
X / 2

tensor([[0.3559, 0.3938, 0.2092],
        [0.4507, 0.4984, 0.3783]])

In [25]:
# mod
X % 2

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [26]:
# power
X ** 2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

## 2. Element Wise

In [28]:
t1 = torch.rand(2, 3)
t2 = torch.rand(2, 3)

In [29]:
# add
t1 + t2

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [30]:
# subtract
t1 - t2

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [31]:
# multiply
t1 * t2

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [32]:
# divide
t1 / t2

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [33]:
# power
t1 ** t2

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

## 3. Reduction

In [39]:
r1 = torch.randint(size = (2, 3), low = 0, high = 10)
r1

tensor([[3, 9, 4],
        [0, 5, 7]])

In [40]:
# sum
torch.sum(r1)

tensor(28)

In [41]:
# sum of columns
torch.sum(r1, dim = 0)

tensor([ 3, 14, 11])

In [42]:
# sum of rows
torch.sum(r1, dim = 1)

tensor([16, 12])

## 4. Reshaping Tensors

In [43]:
n = torch.ones(4, 4)
n

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
# reshape
n.reshape(2, 2, 2, 2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [47]:
# flatten
n.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## 5. NumPy and PyTorch

In [48]:
import numpy as np

In [52]:
t3 = torch.tensor([1, 2, 3])
t3

tensor([1, 2, 3])

In [54]:
type(t3)

torch.Tensor

In [57]:
# convert to numpy array
t4 = t3.numpy()
t4

array([1, 2, 3])

In [58]:
type(t4)

numpy.ndarray

In [59]:
t5 = np.array([1, 6, 10])
t5

array([ 1,  6, 10])

In [60]:
torch.from_numpy(t5)

tensor([ 1,  6, 10])